### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#27]
1. Straighten the captions of the 'User Login' and 'Group' fields on LDAP Matching Rules Screen.
![image.png](https://images.zenhubusercontent.com/5ac379174b5806bc2bcd7057/5414b946-d2bd-4058-845e-b3d3786f9f35)

2. Straighten the caption of the 'User Login' field in Scripting Matching Rule Editor.
![image.png](https://images.zenhubusercontent.com/5ac379174b5806bc2bcd7057/22f22171-1c6e-4ca2-ab85-4bfde8e33071)

3. Enlarge the 'Error' field in LDAP Log (make it 8 or, if possible, 10 lines instead of 4). There is a lot of unused space in the bottom of the screen and the current size makes it hard to read error details, even though scrolling is available.
![image.png](https://images.zenhubusercontent.com/5ac379174b5806bc2bcd7057/ffff29f1-add7-461e-b031-5034698198ee)

4. The names of the 'Applied Roles' and 'Applied Matching Rules' tables on LDAP Matching Rules Screen should be farther from the tables themselves. They will also look better in bold.
![default](https://user-images.githubusercontent.com/38000666/39700388-16d29cc6-520e-11e8-891e-8604072281b8.png)

**Comment by antmarr** [comment]
Done. Please check.

**Comment by smianna** [comment]
1. The captions of the 'User Login' and 'Group' fields on LDAP Matching Rules Screen are still not straightened.

**Comment by antmarr** [comment]
Done. Please check.

**Comment by smianna** [comment]
Verified
